# Generated by Django 3.0.2 on 2020-01-31 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200131_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lenguage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='author',
            name='data_of_birth',
            field=models.DateField(blank=True, help_text='Ingrese fecha de nacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='data_of_death',
            field=models.DateField(blank=True, help_text='Ingrese fecha de su muerte', null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Ingrese el idioma del Libro', max_length=20),
        ),
    ]
